var EMOJI_CATEGORIES = [
  {
    id: "smileys",
    name: "Smileys & Emotion",
    icon: "😀",
    emojis: {
      "😀": ["grinning", "smile", "happy", "joy"],
      "😃": ["smiley", "smile", "happy", "joy"],
      "😄": ["smile", "happy", "joy", "funny"],
      "😁": ["grin", "happy", "smile"],
      "😆": ["laughing", "satisfied", "lol", "haha"],
      "😅": ["sweat_smile", "hot", "happy", "relief"],
      "🤣": ["rofl", "lol", "laugh"],
      "😂": ["joy", "tears", "laugh", "lol"],
      "🙂": ["slightly_smiling", "smile"],
      "🙃": ["upside_down", "silly", "smile"],
      "😉": ["wink", "happy", "mischievous"],
      "😊": ["blush", "smile", "happy", "shy"],
      "😇": ["angel", "halo", "innocent"],
      "🥰": ["smiling_face_with_three_hearts", "love", "affection"],
      "😍": ["heart_eyes", "love", "crush"],
      "🤩": ["star_struck", "wow", "excited"],
      "😘": ["kissing_heart", "love", "affection"],
      "😗": ["kissing", "love"],
      "😚": ["kissing_closed_eyes", "love"],
      "😙": ["kissing_smiling_eyes", "love"],
      "😋": ["yum", "delicious", "hungry"],
      "😛": ["stuck_out_tongue", "silly", "prank"],
      "😜": ["stuck_out_tongue_winking_eye", "wink", "silly"],
      "🤪": ["zany", "crazy", "goofy"],
      "😝": ["stuck_out_tongue_closed_eyes", "silly"],
      "🤑": ["money_mouth", "rich", "dollar"],
      "🤗": ["hugging", "hug", "smile"],
      "🤭": ["hand_over_mouth", "whoops", "shock"],
      "🤫": ["shushing", "quiet", "shh"],
      "🤔": ["thinking", "hmmm", "think"],
      "🤐": ["zipper_mouth", "secret", "quiet"],
      "🤨": ["raised_eyebrow", "suspicious", "doubt"],
      "😐": ["neutral", "meh"],
      "😑": ["expressionless", "meh"],
      "😶": ["no_mouth", "quiet", "silent"],
      "😏": ["smirk", "smug", "sarcastic"],
      "😒": ["unamused", "bored", "meh"],
      "🙄": ["rolling_eyes", "eyeroll", "frustrated"],
      "😬": ["grimacing", "awkward", "teeth"],
      "🤥": ["lying", "liar", "nose"],
      "😌": ["relieved", "relaxed", "phew"],
      "😔": ["pensive", "sad", "upset"],
      "😪": ["sleepy", "tired", "nap"],
      "🤤": ["drooling", "delicious"],
      "😴": ["sleeping", "tired", "zzz"],
      "😷": ["mask", "sick", "doctor"],
      "🤒": ["thermometer", "sick", "fever"],
      "🤕": ["bandage", "hurt", "injury"],
      "🤢": ["nauseated", "sick", "gross"],
      "🤮": ["vomiting", "sick", "puke"],
      "🤧": ["sneezing", "sick", "allergy"],
      "🥵": ["hot", "heat", "red"],
      "🥶": ["cold", "frozen", "ice"],
      "🥴": ["woozy", "dizzy", "drunk"],
      "😵": ["dizzy", "dead", "knocked_out"],
      "🤯": ["exploding_head", "mind_blown", "wow"],
      "🤠": ["cowboy", "hat"],
      "🥳": ["partying", "celebration", "birthday"],
      "😎": ["sunglasses", "cool", "summer"],
      "🤓": ["nerd", "geek", "glasses"],
      "🧐": ["monocle", "rich", "inspect"],
      "😕": ["confused", "hmmm", "weird"],
      "😟": ["worried", "concern", "nervous"],
      "🙁": ["frowning", "sad"],
      "☹️": ["frown", "sad"],
      "😮": ["open_mouth", "surprise", "wow"],
      "😯": ["hushed", "surprise", "quiet"],
      "😲": ["astonished", "shocked", "wow"],
      "😳": ["flushed", "embarrassed", "shocked"],
      "🥺": ["pleading", "begging", "sad"],
      "😦": ["frowning_with_open_mouth", "shocked"],
      "😧": ["anguished", "shocked"],
      "😨": ["fearful", "scared", "shocked"],
      "😰": ["cold_sweat", "scared", "nervous"],
      "😥": ["sad_relieved", "phew", "sweat"],
      "😢": ["cry", "sad", "tear"],
      "😭": ["sob", "crying", "sad", "tears"],
      "😱": ["scream", "scared", "shocked"],
      "😖": ["confounded", "frustrated"],
      "😣": ["persevere", "struggling"],
      "😞": ["disappointed", "sad"],
      "😓": ["sweat", "sad", "tired"],
      "😩": ["weary", "tired", "frustrated"],
      "😫": ["tired", "frustrated"],
      "🥱": ["yawning", "tired", "sleepy"],
      "😤": ["triumph", "angry", "huff"],
      "😡": ["rage", "angry", "mad"],
      "😠": ["angry", "mad", "annoyed"],
      "🤬": ["cursing", "angry", "mad"],
      "😈": ["smiling_imp", "devil", "evil"],
      "👿": ["imp", "devil", "angry"],
      "💀": ["skull", "dead", "skeleton"],
      "☠️": ["skull_and_crossbones", "dead", "danger"],
      "💩": ["poop", "shit", "funny"],
      "🤡": ["clown", "funny", "scary"],
      "👹": ["ogre", "monster", "scary"],
      "👺": ["goblin", "monster", "scary"],
      "👻": ["ghost", "scary", "halloween"],
      "👽": ["alien", "ufo", "space"],
      "👾": ["space_invader", "game", "retro"],
      "🤖": ["robot", "bot", "future"],
      "💋": ["kiss", "love", "lips"],
      "💌": ["love_letter", "love", "mail"],
      "💘": ["cupid", "love", "heart"],
      "💝": ["gift_heart", "love", "present"],
      "💖": ["sparkling_heart", "love", "shiny"],
      "💗": ["growing_heart", "love"],
      "💓": ["beating_heart", "love"],
      "💞": ["revolving_hearts", "love"],
      "💕": ["two_hearts", "love"],
      "💟": ["heart_decoration", "love"],
      "❣️": ["heart_exclamation", "love"],
      "💔": ["broken_heart", "sad", "love"],
      "❤️": ["heart", "love", "red"],
      "🧡": ["orange_heart", "love"],
      "💛": ["yellow_heart", "love"],
      "💚": ["green_heart", "love"],
      "💙": ["blue_heart", "love"],
      "💜": ["purple_heart", "love"],
      "🤎": ["brown_heart", "love"],
      "🖤": ["black_heart", "love"],
      "🤍": ["white_heart", "love"],
      "💯": ["100", "score", "perfect"],
      "💢": ["anger", "angry", "mad"],
      "💥": ["collision", "boom", "explosion"],
      "💫": ["dizzy", "star", "sparkle"],
      "💦": ["sweat_drops", "water", "wet"],
      "💨": ["dash", "wind", "fast"],
      "🕳️": ["hole"],
      "💣": ["bomb", "explosion", "danger"],
      "💬": ["speech_balloon", "chat", "message"],
      "👁️‍🗨️": ["eye_in_speech_bubble"],
      "🗨️": ["left_speech_bubble"],
      "🗯️": ["right_anger_bubble"],
      "💭": ["thought_balloon", "think"],
      "💤": ["zzz", "sleeping", "tired"]
    }
  },
  {
    id: "people",
    name: "People & Body",
    icon: "👋",
    emojis: {
      "👋": ["wave", "hello", "goodbye"],
      "🤚": ["raised_back_of_hand"],
      "🖐": ["raised_hand_with_fingers_splayed"],
      "✋": ["raised_hand", "stop", "high_five"],
      "🖖": ["vulcan_salute", "spock", "star_trek"],
      "👌": ["ok", "perfect", "good"],
      "🤌": ["pinched_fingers", "italian"],
      "🤏": ["pinching_hand", "small"],
      "✌": ["v", "peace", "victory"],
      "🤞": ["fingers_crossed", "luck"],
      "🤟": ["love_you_gesture", "love"],
      "🤘": ["rock_on", "metal"],
      "🤙": ["call_me", "phone"],
      "👈": ["point_left", "direction"],
      "👉": ["point_right", "direction"],
      "👆": ["point_up", "direction"],
      "🖕": ["middle_finger", "angry"],
      "👇": ["point_down", "direction"],
      "☝": ["index_pointing_up"],
      "👍": ["thumbsup", "good", "yes"],
      "👎": ["thumbsdown", "bad", "no"],
      "✊": ["fist", "power"],
      "👊": ["oncoming_fist", "punch"],
      "🤛": ["left_facing_fist"],
      "🤜": ["right_facing_fist"],
      "👏": ["clap", "good", "applause"],
      "🙌": ["raised_hands", "celebration", "hooray"],
      "👐": ["open_hands"],
      "🤲": ["palms_up_together", "prayer"],
      "🤝": ["handshake", "agreement", "deal"],
      "🙏": ["pray", "please", "thanks"],
      "✍": ["writing_hand", "write"],
      "💅": ["nail_care", "beauty", "fashion"],
      "🤳": ["selfie", "camera", "phone"],
      "💪": ["muscle", "strong", "power"],
      "🦾": ["mechanical_arm", "robot"],
      "🦿": ["mechanical_leg", "robot"],
      "🦵": ["leg"],
      "🦶": ["foot"],
      "👂": ["ear", "hear"],
      "🦻": ["hearing_aid"],
      "👃": ["nose", "smell"],
      "🧠": ["brain", "think", "smart"],
      "🫀": ["anatomical_heart"],
      "🫁": ["lungs"],
      "🦷": ["tooth", "dentist"],
      "🦴": ["bone", "skeleton"],
      "👀": ["eyes", "look", "see"],
      "👁": ["eye", "look"],
      "👅": ["tongue", "taste"],
      "👄": ["mouth", "lips", "kiss"],
      "👶": ["baby", "child", "young"],
      "🧒": ["child"],
      "👦": ["boy", "child", "young"],
      "👧": ["girl", "child", "young"],
      "🧑": ["person"],
      "👱": ["blonde_hair"],
      "👨": ["man", "adult"],
      "🧔": ["bearded_person"],
      "👩": ["woman", "adult"],
      "🧓": ["older_person"],
      "👴": ["old_man", "adult", "elder"],
      "👵": ["old_woman", "adult", "elder"],
      "🙇": ["bow", "sorry", "pray"],
      "💁": ["information_desk_person", "sassy", "help"],
      "🙅": ["no_good", "no", "stop"],
      "🙆": ["ok_gesture", "ok", "yes"],
      "🙋": ["raising_hand", "help", "question"],
      "🧏": ["deaf_person"]
    }
  },
  {
    id: "animals",
    name: "Animals & Nature",
    icon: "🐶",
    emojis: {
      "😺": ["smiley_cat", "happy", "animal"],
      "😸": ["smile_cat", "happy", "animal"],
      "😻": ["heart_eyes_cat", "love", "animal"],
      "😼": ["smirk_cat", "animal"],
      "😽": ["kissing_cat", "love", "animal"],
      "🙀": ["scream_cat", "scared", "animal"],
      "😿": ["crying_cat", "sad", "animal"],
      "😾": ["pouting_cat", "angry", "animal"],
      "🙈": ["see_no_evil", "monkey", "animal"],
      "🙉": ["hear_no_evil", "monkey", "animal"],
      "🙊": ["speak_no_evil", "monkey", "animal"],
      "🐶": ["dog", "animal", "pet"],
      "🐱": ["cat", "animal", "pet"],
      "🐭": ["mouse", "animal"],
      "🐹": ["hamster", "animal", "pet"],
      "🐰": ["rabbit", "animal", "bunny"],
      "🦊": ["fox", "animal"],
      "🐻": ["bear", "animal"],
      "🐼": ["panda", "animal"],
      "🐻‍❄️": ["polar_bear", "animal"],
      "🐨": ["koala", "animal"],
      "🐯": ["tiger", "animal"],
      "🦁": ["lion", "animal"],
      "🐮": ["cow", "animal"],
      "🐷": ["pig", "animal"],
      "🐸": ["frog", "animal"],
      "🐵": ["monkey", "animal"],
      "🐔": ["chicken", "animal", "bird"],
      "🐧": ["penguin", "animal", "bird"],
      "🐦": ["bird", "animal"],
      "🐤": ["baby_chick", "animal", "bird"],
      "🦆": ["duck", "animal", "bird"],
      "🦅": ["eagle", "animal", "bird"],
      "🦉": ["owl", "animal", "bird"],
      "🦇": ["bat", "animal"],
      "🐺": ["wolf", "animal"],
      "🐗": ["boar", "animal"],
      "🐴": ["horse", "animal"],
      "🦄": ["unicorn", "animal", "magic"],
      "🐝": ["bee", "animal", "bug"],
      "🐛": ["bug", "animal", "insect"],
      "🦋": ["butterfly", "animal", "insect"],
      "🐌": ["snail", "animal", "bug"],
      "🐞": ["ladybug", "animal", "bug"],
      "🐜": ["ant", "animal", "bug"],
      "🦟": ["mosquito", "animal", "bug"],
      "🕷️": ["spider", "animal", "bug"],
      "🕸️": ["spider_web", "animal", "bug"],
      "🐢": ["turtle", "animal"],
      "🐍": ["snake", "animal"],
      "🦎": ["lizard", "animal"],
      "🦖": ["t-rex", "animal", "dinosaur"],
      "🦕": ["sauropod", "animal", "dinosaur"],
      "🐙": ["octopus", "animal", "ocean"],
      "🦑": ["squid", "animal", "ocean"],
      "🦐": ["shrimp", "animal", "ocean"],
      "🦞": ["lobster", "animal", "ocean"],
      "🦀": ["crab", "animal", "ocean"],
      "🐡": ["blowfish", "animal", "ocean"],
      "🐠": ["tropical_fish", "animal", "ocean"],
      "🐟": ["fish", "animal", "ocean"],
      "🐬": ["dolphin", "animal", "ocean"],
      "🐳": ["spouting_whale", "animal", "ocean"],
      "🐋": ["whale", "animal", "ocean"],
      "🦈": ["shark", "animal", "ocean"],
      "🐊": ["crocodile", "animal"],
      "🐅": ["tiger2", "animal"],
      "🐆": ["leopard", "animal"],
      "🦓": ["zebra", "animal"],
      "🦍": ["gorilla", "animal"],
      "🦧": ["orangutan", "animal"],
      "🐘": ["elephant", "animal"],
      "🦛": ["hippopotamus", "animal"],
      "🦏": ["rhinoceros", "animal"],
      "🐪": ["camel", "animal"],
      "🐫": ["two_hump_camel", "animal"],
      "🦒": ["giraffe", "animal"],
      "🦘": ["kangaroo", "animal"],
      "🐃": ["water_buffalo", "animal"],
      "🐂": ["ox", "animal"],
      "🐄": ["cow2", "animal"],
      "🐎": ["racehorse", "animal"],
      "🐖": ["pig2", "animal"],
      "🐏": ["ram", "animal"],
      "🐑": ["sheep", "animal"],
      "🦙": ["llama", "animal"],
      "🐐": ["goat", "animal"],
      "🦌": ["deer", "animal"],
      "🐕": ["dog2", "animal"],
      "🐩": ["poodle", "animal", "dog"],
      "🦮": ["guide_dog", "animal", "dog"],
      "🐕‍🦺": ["service_dog", "animal", "dog"],
      "🐈": ["cat2", "animal"],
      "🐓": ["rooster", "animal", "bird"],
      "🦃": ["turkey", "animal", "bird"],
      "🦚": ["peacock", "animal", "bird"],
      "🦜": ["parrot", "animal", "bird"],
      "🦢": ["swan", "animal", "bird"],
      "🦩": ["flamingo", "animal", "bird"],
      "🕊️": ["dove", "animal", "bird", "peace"],
      "🐇": ["rabbit2", "animal"],
      "🦝": ["raccoon", "animal"],
      "🦨": ["skunk", "animal"],
      "🦡": ["badger", "animal"],
      "🦦": ["otter", "animal"],
      "🦥": ["sloth", "animal"],
      "🐁": ["mouse2", "animal"],
      "🐀": ["rat", "animal"],
      "🐿️": ["chipmunk", "animal"],
      "🦔": ["hedgehog", "animal"],
      "🌲": ["evergreen_tree", "plant", "nature"],
      "🌳": ["deciduous_tree", "plant", "nature"],
      "🌴": ["palm_tree", "plant", "nature"],
      "🌵": ["cactus", "plant", "nature"],
      "🌶️": ["hot_pepper", "plant", "food"],
      "🌷": ["tulip", "flower", "nature"],
      "🌸": ["cherry_blossom", "flower", "nature"],
      "🌹": ["rose", "flower", "nature"],
      "🌺": ["hibiscus", "flower", "nature"],
      "🌻": ["sunflower", "flower", "nature"],
      "🌼": ["blossom", "flower", "nature"],
      "🌾": ["ear_of_rice", "plant", "nature"],
      "🌿": ["herb", "plant", "nature"],
      "🥀": ["wilted_flower", "flower", "nature", "sad", "dying rose", "dying flower"],
      "🍀": ["four_leaf_clover", "plant", "nature", "luck"],
      "🍁": ["maple_leaf", "plant", "nature", "fall"],
      "🍂": ["fallen_leaf", "plant", "nature", "fall"],
      "🍃": ["leaves", "plant", "nature"],
      "🍄": ["mushroom", "plant", "nature"],
      "🌰": ["chestnut", "plant", "nature"]
    }
  },
  {
    id: "food",
    name: "Food & Drink",
    icon: "🍔",
    emojis: {
      "🍕": ["pizza", "food", "delicious"],
      "🍔": ["burger", "food"],
      "🍆": ["eggplant", "food"],
      "🍟": ["fries", "food"],
      "🌭": ["hotdog", "food"],
      "🍿": ["popcorn", "food", "movie"],
      "🧂": ["salt", "food"],
      "🥓": ["bacon", "food"],
      "🥚": ["egg", "food"],
      "🍳": ["fried_egg", "food", "breakfast"],
      "🧇": ["waffle", "food", "breakfast"],
      "🥞": ["pancakes", "food", "breakfast"],
      "🧈": ["butter", "food"],
      "🍞": ["bread", "food"],
      "🥐": ["croissant", "food"],
      "🥨": ["pretzel", "food"],
      "🥯": ["bagel", "food"],
      "🥖": ["baguette_bread", "food"],
      "🧀": ["cheese", "food"],
      "🥗": ["green_salad", "food", "healthy"],
      "🥙": ["stuffed_flatbread", "food"],
      "🥪": ["sandwich", "food"],
      "🌮": ["taco", "food"],
      "🌽": ["ear_of_corn", "food"],
      "🌯": ["burrito", "food"],
      "🥫": ["canned_food", "food"],
      "🍖": ["meat_on_bone", "food", "meat"],
      "🍗": ["poultry_leg", "food", "meat"],
      "🥩": ["cut_of_meat", "food", "meat"],
      "🍠": ["sweet_potato", "food"],
      "🥟": ["dumpling", "food"],
      "🥡": ["takeout_box", "food"],
      "🍱": ["bento", "food"],
      "🍘": ["rice_cracker", "food"],
      "🍙": ["rice_ball", "food"],
      "🍚": ["rice", "food"],
      "🍛": ["curry", "food"],
      "🍜": ["ramen", "food", "noodle"],
      "🍝": ["spaghetti", "food", "pasta"],
      "🍲": ["stew", "food", "soup"],
      "🥘": ["shallow_pan_of_food", "food", "paella"],
      "🥣": ["bowl_with_spoon", "food", "soup", "cereal"],
      "🥗": ["green_salad", "food"],
      "🍣": ["sushi", "food"],
      "🍦": ["icecream", "food", "dessert"],
      "🍧": ["shaved_ice", "food", "dessert"],
      "🍨": ["ice_cream", "food", "dessert"],
      "🍩": ["donut", "food", "dessert"],
      "🍪": ["cookie", "food", "dessert"],
      "🎂": ["cake", "birthday", "celebration", "food", "dessert"],
      "🍰": ["shortcake", "food", "dessert"],
      "🧁": ["cupcake", "food", "dessert"],
      "🥧": ["pie", "food", "dessert"],
      "🍫": ["chocolate", "food", "dessert"],
      "🍬": ["candy", "food", "dessert"],
      "🍭": ["lollipop", "food", "dessert"],
      "🍮": ["custard", "food", "dessert"],
      "🍯": ["honey_pot", "food", "sweet"],
      "🍼": ["baby_bottle", "drink", "milk"],
      "🥛": ["milk", "drink"],
      "☕": ["coffee", "drink", "morning"],
      "🍵": ["tea", "drink"],
      "🍶": ["sake", "drink"],
      "🍾": ["champagne", "drink", "party", "celebration"],
      "🍷": ["wine", "drink", "party"],
      "🍸": ["cocktail", "drink", "party"],
      "🍹": ["tropical_drink", "drink", "party"],
      "🍺": ["beer", "drink", "party"],
      "🍻": ["beers", "drink", "party", "cheers"],
      "🥂": ["clinking_glasses", "drink", "party", "cheers"],
      "🥃": ["tumbler_glass", "drink", "liquor"],
      "🥤": ["cup_with_straw", "drink"],
      "🧃": ["beverage_box", "drink", "juice"],
      "🧉": ["mate", "drink"],
      "🧊": ["ice", "cold"],
      "🍥": ["fishcake", "japan", "food"],
      "🥢": ["chopsticks", "japan", "food"],
      "🥠": ["fortune_cookie", "japan", "food"],
      "🏺": ["amphora", "food", "drink"]
    }
  },
  {
    id: "travel",
    name: "Travel & Places",
    icon: "✈️",
    emojis: {
      "🚗": ["car", "transport"],
      "🚕": ["taxi", "transport"],
      "🚙": ["blue_car", "transport"],
      "🚌": ["bus", "transport"],
      "🚎": ["trolleybus", "transport"],
      "🏎️": ["racing_car", "transport", "fast"],
      "🚓": ["police_car", "transport"],
      "🚑": ["ambulance", "transport", "health"],
      "🚒": ["fire_engine", "transport"],
      "🚐": ["minibus", "transport"],
      "🚚": ["truck", "transport"],
      "🚛": ["articulated_lurry", "transport"],
      "🚜": ["tractor", "transport"],
      "🚲": ["bicycle", "transport"],
      "🛴": ["kick_scooter", "transport"],
      "🛹": ["skateboard", "transport"],
      "🛺": ["auto_rickshaw", "transport"],
      "🏍": ["motorcycle", "transport"],
      "🛵": ["motor_scooter", "transport"],
      "🛸": ["ufo", "space", "alien"],
      "🚁": ["helicopter", "transport"],
      "🛶": ["canoe", "transport"],
      "⛵": ["sailboat", "transport"],
      "🚤": ["speedboat", "transport"],
      "🛳️": ["passenger_ship", "transport"],
      "⛴️": ["ferry", "transport"],
      "🛥️": ["motor_boat", "transport"],
      "🚢": ["ship", "transport"],
      "✈️": ["airplane", "transport", "travel"],
      "🛩️": ["small_airplane", "transport"],
      "🛫": ["airplane_departure", "travel"],
      "🛬": ["airplane_arrival", "travel"],
      "🪂": ["parachute"],
      "🛰️": ["satellite", "space"],
      "🚀": ["rocket", "space", "launch", "fast"],
      "🌍": ["earth_africa", "globe", "world", "international"],
      "🌎": ["earth_americas", "globe", "world", "international"],
      "🌏": ["earth_asia", "globe", "world", "international"],
      "🌐": ["globe_with_meridians", "world", "global", "international"],
      "🗺️": ["world_map", "travel"],
      "🗾": ["japan", "map"],
      "🧭": ["compass", "travel", "direction"],
      "🏔️": ["snow_capped_mountain", "nature"],
      "⛰️": ["mountain", "nature"],
      "🌋": ["volcano", "nature", "disaster"],
      "🗻": ["mount_fuji", "nature", "japan"],
      "🏕️": ["camping", "nature", "tent"],
      "🏖️": ["beach_umbrella", "nature", "vacation"],
      "🏜️": ["desert", "nature"],
      "🏝️": ["desert_island", "nature", "vacation"],
      "🏞️": ["national_park", "nature"],
      "🏟️": ["stadium", "building", "sports"],
      "🏛️": ["classical_building", "building", "art"],
      "🏗️": ["building_construction", "building", "crane"],
      "🧱": ["brick", "building"],
      "🏘️": ["houses", "building"],
      "🏚️": ["derelict_house", "building"],
      "🏠": ["house", "building", "home"],
      "🏡": ["house_with_garden", "building", "home"],
      "🏢": ["office", "building", "work"],
      "🏣": ["post_office", "building"],
      "🏤": ["european_post_office", "building"],
      "🏥": ["hospital", "building", "health"],
      "🏦": ["bank", "building", "money"],
      "🏨": ["hotel", "building", "travel"],
      "🏩": ["love_hotel", "building", "love"],
      "🏪": ["convenience_store", "building"],
      "🏫": ["school", "building", "education"],
      "🏬": ["department_store", "building", "shopping"],
      "🏭": ["factory", "building", "industry"],
      "🏯": ["japanese_castle", "building", "japan"],
      "🏰": ["european_castle", "building"],
      "💒": ["wedding", "building", "love"],
      "🗼": ["tokyo_tower", "building", "japan"],
      "🗽": ["statue_of_liberty", "building", "newyork"],
      "⛪": ["church", "building", "religion"],
      "🕌": ["mosque", "building", "religion"],
      "🛕": ["hindu_temple", "building", "religion"],
      "🕍": ["synagogue", "building", "religion"],
      "⛩️": ["shinto_shrine", "building", "religion", "japan"],
      "🕋": ["kaaba", "building", "religion"],
      "⛲": ["fountain"],
      "⛺": ["tent", "camping"],
      "🗿": ["moai", "statue", "easter_island"]
    }
  },
  {
    id: "objects",
    name: "Objects & Activities",
    icon: "💡",
    emojis: {
      "⌚": ["watch", "time", "technology"],
      "📱": ["iphone", "phone", "technology"],
      "📲": ["calling", "phone"],
      "📳": ["phone", "technology", "vibration"],
      "💻": ["computer", "technology", "laptop"],
      "⌨️": ["keyboard", "technology"],
      "🖥️": ["desktop_computer", "technology"],
      "🖱️": ["computer_mouse", "technology"],
      "🖲️": ["trackball", "technology"],
      "🕹️": ["joystick", "technology", "game"],
      "🎮": ["video_game", "game", "technology", "play"],
      "📠": ["fax", "technology"],
      "📺": ["tv", "technology", "television"],
      "📷": ["camera", "technology", "photo"],
      "📸": ["camera_with_flash", "photo"],
      "📹": ["video_camera", "photo", "film"],
      "📼": ["vhs", "retro", "video"],
      "🔍": ["search", "find", "magnifying_glass"],
      "🔎": ["search_right", "find"],
      "🕯️": ["candle", "light", "fire"],
      "💡": ["bulb", "idea", "light"],
      "🔦": ["flashlight", "light"],
      "🏮": ["izakaya_lantern", "light", "japan"],
      "📔": ["notebook_with_decorative_cover", "book", "write"],
      "📕": ["closed_book", "read", "study"],
      "📖": ["book", "read", "open"],
      "📗": ["green_book", "read"],
      "📘": ["blue_book", "read"],
      "📙": ["orange_book", "read"],
      "📚": ["books", "read", "study", "library"],
      "📓": ["notebook", "write", "study"],
      "📒": ["ledger", "write", "notes"],
      "📃": ["page_with_curl", "document"],
      "📜": ["scroll", "history", "document"],
      "📄": ["page_facing_up", "document", "file"],
      "📰": ["newspaper", "news", "press"],
      "🗞️": ["rolled_up_newspaper", "news", "press"],
      "📑": ["bookmark_tabs", "tabs", "pages"],
      "🔖": ["bookmark", "mark"],
      "🏷️": ["label", "tag"],
      "💰": ["moneybag", "money", "rich", "wealth"],
      "💴": ["yen", "money", "japan"],
      "💵": ["dollar", "money", "usa", "cash"],
      "💶": ["euro", "money", "europe"],
      "💷": ["pound", "money", "uk"],
      "💸": ["money_with_wings", "money", "cash", "spend"],
      "💳": ["credit_card", "money", "pay"],
      "💹": ["chart_with_upwards_trend", "money", "stock", "graph"],
      "💱": ["currency_exchange", "money", "exchange"],
      "💲": ["heavy_dollar_sign", "money"],
      "✉️": ["envelope", "mail", "letter"],
      "📧": ["e-mail", "mail", "email", "communication"],
      "📨": ["incoming_envelope", "mail", "receive"],
      "📩": ["envelope_with_arrow", "mail", "send"],
      "📤": ["outbox_tray", "mail", "send"],
      "📥": ["inbox_tray", "mail", "receive"],
      "📦": ["package", "mail", "delivery", "box"],
      "📫": ["closed_mailbox_with_raised_flag", "mail", "post"],
      "📪": ["closed_mailbox_with_lowered_flag", "mail", "post"],
      "📬": ["open_mailbox_with_raised_flag", "mail", "post"],
      "📭": ["open_mailbox_with_lowered_flag", "mail", "post"],
      "📮": ["postbox", "mail", "letterbox"],
      "🗳️": ["ballot_box_with_ballot", "vote", "election"],
      "✏️": ["pencil", "write", "draw"],
      "✒️": ["black_nib", "write", "pen"],
      "🖋️": ["fountain_pen", "write", "pen"],
      "🖊️": ["pen", "write"],
      "🖌️": ["paintbrush", "art", "draw", "paint"],
      "🖍": ["crayon", "art", "draw", "color"],
      "📝": ["memo", "write", "note", "document"],
      "📁": ["file_folder", "folder", "directory"],
      "📂": ["open_file_folder", "folder", "directory"],
      "📅": ["calendar", "time", "date", "schedule"],
      "📆": ["tear_off_calendar", "time", "date", "schedule"],
      "📌": ["pushpin", "marker", "pin", "location"],
      "📍": ["round_pushpin", "marker", "pin", "location"],
      "📎": ["paperclip", "attachment"],
      "📏": ["straight_ruler", "measure", "math"],
      "📐": ["triangular_ruler", "measure", "math"],
      "⚽": ["soccer", "sports", "football"],
      "⚾": ["baseball", "sports"],
      "🥎": ["softball", "sports"],
      "🏀": ["basketball", "sports"],
      "🏐": ["volleyball", "sports"],
      "🏈": ["football", "sports"],
      "🏉": ["rugby_football", "sports"],
      "🎾": ["tennis", "sports"],
      "🥏": ["flying_disc", "sports"],
      "🎳": ["bowling", "sports"],
      "🏏": ["cricket_game", "sports"],
      "🏑": ["field_hockey", "sports"],
      "🏒": ["ice_hockey", "sports"],
      "🥍": ["lacrosse", "sports"],
      "🏓": ["ping_pong", "sports"],
      "🏸": ["badminton", "sports"],
      "🥊": ["boxing_glove", "sports"],
      "🥋": ["martial_arts_uniform", "sports"],
      "🥅": ["goal_net", "sports"],
      "⛳": ["golf", "sports"],
      "⛸": ["ice_skate", "sports"],
      "🎣": ["fishing_pole_and_fish", "sports", "hobby"],
      "🤿": ["diving_mask", "sports", "water"],
      "🎽": ["running_shirt_with_sash", "sports"],
      "🎿": ["ski", "sports", "winter"],
      "🛷": ["sled", "sports", "winter"],
      "🥌": ["curling_stone", "sports", "winter"],
      "🎯": ["dart", "game", "target"],
      "🪀": ["yo_yo", "game", "toy"],
      "🪁": ["kite", "game", "toy"],
      "🎱": ["8ball", "game", "pool"],
      "🔮": ["crystal_ball", "magic", "fortune"],
      "🧿": ["nazar_amulet", "magic", "evil_eye"],
      "🎲": ["game_die", "game", "dice"],
      "🧩": ["jigsaw", "game", "puzzle"],
      "🧸": ["teddy_bear", "toy"],
      "♠️": ["spades", "game", "cards"],
      "♥️": ["hearts", "game", "cards"],
      "♦️": ["diamonds", "game", "cards"],
      "♣️": ["clubs", "game", "cards"],
      "🃏": ["black_joker", "game", "cards"],
      "🀄": ["mahjong", "game"],
      "🎴": ["flower_playing_cards", "game"],
      "🎭": ["performing_arts", "art", "theater", "drama"],
      "🖼": ["framed_picture", "art", "photo"],
      "🎨": ["art", "painting", "palette"],
      "🧵": ["thread", "sewing", "craft"],
      "🧶": ["yarn", "sewing", "craft"],
      "🎼": ["musical_score", "music", "art"],
      "🎵": ["musical_note", "music", "art"],
      "🎶": ["notes", "music", "art"],
      "🎙️": ["studio_microphone", "music", "recording"],
      "🎚️": ["level_slider", "music", "recording"],
      "🎛️": ["control_knobs", "music", "recording"],
      "🎤": ["microphone", "music", "sing"],
      "🎧": ["headphones", "music", "listen"],
      "📻": ["radio", "music", "podcast"],
      "🎷": ["saxophone", "music", "instrument"],
      "🎸": ["guitar", "music", "instrument"],
      "🎹": ["musical_keyboard", "music", "instrument", "piano"],
      "🎺": ["trumpet", "music", "instrument"],
      "🎻": ["violin", "music", "instrument"],
      "🪕": ["banjo", "music", "instrument"],
      "🥁": ["drum", "music", "instrument"]
    }
  },
  {
    id: "symbols",
    name: "Symbols",
    icon: "🔣",
    emojis: {
      "✨": ["sparkles", "shiny", "magic"],
      "🔥": ["fire", "hot", "lit"],
      "⭐": ["star", "shiny"],
      "🌟": ["glowing_star", "shiny"],
      "🌈": ["rainbow", "color", "happy"],
      "☀️": ["sun", "weather", "hot"],
      "🌙": ["moon", "night"],
      "☁️": ["cloud", "weather"],
      "❄️": ["snowflake", "cold", "winter"],
      "⚡": ["zap", "lightning", "fast", "energy"],
      "🎉": ["tada", "celebration", "party"],
      "🎈": ["balloon", "celebration", "party"],
      "🎁": ["gift", "present", "birthday"],
      "⌛": ["hourglass", "time"],
      "⏳": ["hourglass_flowing_sand", "time"],
      "⏰": ["alarm_clock", "time"],
      "⏱️": ["stopwatch", "time"],
      "⏲️": ["timer_clock", "time"],
      "🕰️": ["mantelpiece_clock", "time"],
      "🕛": ["clock12", "time"],
      "🕧": ["clock1230", "time"],
      "🕐": ["clock1", "time"],
      "🕜": ["clock130", "time"],
      "🕑": ["clock2", "time"],
      "🕝": ["clock230", "time"],
      "🕒": ["clock3", "time"],
      "🕞": ["clock330", "time"],
      "🕓": ["clock4", "time"],
      "🕟": ["clock430", "time"],
      "🕔": ["clock5", "time"],
      "🕠": ["clock530", "time"],
      "🕕": ["clock6", "time"],
      "🕡": ["clock630", "time"],
      "🕖": ["clock7", "time"],
      "🕢": ["clock730", "time"],
      "🕗": ["clock8", "time"],
      "🕣": ["clock830", "time"],
      "🕘": ["clock9", "time"],
      "🕤": ["clock930", "time"],
      "🕙": ["clock10", "time"],
      "🕥": ["clock1030", "time"],
      "🕚": ["clock11", "time"],
      "🕦": ["clock1130", "time"]
    }
  },
  {
    id: "horoscopes",
    name: "Horoscopes",
    icon: "♈",
    emojis: {
      "♈": ["aries", "zodiac", "horoscope"],
      "♉": ["taurus", "zodiac", "horoscope"],
      "♊": ["gemini", "zodiac", "horoscope"],
      "♋": ["cancer", "zodiac", "horoscope"],
      "♌": ["leo", "zodiac", "horoscope"],
      "♍": ["virgo", "zodiac", "horoscope"],
      "♎": ["libra", "zodiac", "horoscope"],
      "♏": ["scorpio", "zodiac", "horoscope"],
      "♐": ["sagittarius", "zodiac", "horoscope"],
      "♑": ["capricorn", "zodiac", "horoscope"],
      "♒": ["aquarius", "zodiac", "horoscope"],
      "♓": ["pisces", "zodiac", "horoscope"]
    }
  }
];
